apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: dm-secretstore
  namespace: application
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-north-1
      auth:
        jwt:
          serviceAccountRef:
            name: dm-frontend-sa